// Generated by CoffeeScript 1.3.3
(function() {
  var func, timeout;

  timeout = false;

  func = function() {};

  window.onscroll = function() {
    if (timeout) {
      clearTimeout(timeout);
    }
    timeout = setTimeout(func, 100);
  };

}).call(this);
